apiVersion: v1
kind: Service
metadata:
  name: golang-app-service
  namespace: default
spec:
  # NodePort exposes the service on each Node's IP at a static port (30080)
  type: NodePort
  selector:
    app: golang-app
  ports:
  - port: 8080        # Port exposed internally inside the cluster
    targetPort: 8080  # Port on the Pod's container
    nodePort: 30080   # Port exposed on host node (range: 30000-32767)
